config/routes.rb
Rails.application.routes.draw do
  resources :serves
  resources :staffs
  resources :services
  resources :rooms
  resources :room_prices
  resources :payment_infos
  resources :hotels
  resources :checkins
  resources :buys
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ApplicationRecord
end

app/models/checkin.rb
class Checkin < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/payment_info.rb
class PaymentInfo < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/room_price.rb
class RoomPrice < ApplicationRecord
end

app/models/serve.rb
class Serve < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  # GET /buys
  # GET /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  # GET /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  # POST /buys.json
  def create
    @buy = Buy.new(buy_params)

    respond_to do |format|
      if @buy.save
        format.html { redirect_to @buy, notice: 'Buy was successfully created.' }
        format.json { render :show, status: :created, location: @buy }
      else
        format.html { render :new }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buys/1
  # PATCH/PUT /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: 'Buy was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy }
      else
        format.html { render :edit }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1
  # DELETE /buys/1.json
  def destroy
    @buy.destroy
    respond_to do |format|
      format.html { redirect_to buys_url, notice: 'Buy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_params
      params.require(:buy).permit(:serviceId, :checkinId, :price)
    end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :age, :jobTitle, :phoneNumber, :address, :City, :State, :Country, :hotelId)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/room_prices_helper.rb
module RoomPricesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/serves_helper.rb
module ServesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff, local: true) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :staff_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :staff_age %>
  </div>

  <div class="field">
    <%= form.label :jobTitle %>
    <%= form.text_field :jobTitle, id: :staff_jobTitle %>
  </div>

  <div class="field">
    <%= form.label :phoneNumber %>
    <%= form.text_field :phoneNumber, id: :staff_phoneNumber %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :staff_address %>
  </div>

  <div class="field">
    <%= form.label :City %>
    <%= form.text_field :City, id: :staff_City %>
  </div>

  <div class="field">
    <%= form.label :State %>
    <%= form.text_field :State, id: :staff_State %>
  </div>

  <div class="field">
    <%= form.label :Country %>
    <%= form.text_field :Country, id: :staff_Country %>
  </div>

  <div class="field">
    <%= form.label :hotelId %>
    <%= form.number_field :hotelId, id: :staff_hotelId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Jobtitle</th>
      <th>Phonenumber</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Hotelid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.age %></td>
        <td><%= staff.jobTitle %></td>
        <td><%= staff.phoneNumber %></td>
        <td><%= staff.address %></td>
        <td><%= staff.City %></td>
        <td><%= staff.State %></td>
        <td><%= staff.Country %></td>
        <td><%= staff.hotelId %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @staff.age %>
</p>

<p>
  <strong>Jobtitle:</strong>
  <%= @staff.jobTitle %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @staff.phoneNumber %>
</p>

<p>
  <strong>Address:</strong>
  <%= @staff.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @staff.City %>
</p>

<p>
  <strong>State:</strong>
  <%= @staff.State %>
</p>

<p>
  <strong>Country:</strong>
  <%= @staff.Country %>
</p>

<p>
  <strong>Hotelid:</strong>
  <%= @staff.hotelId %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>