config/routes.rb
Rails.application.routes.draw do
  resources :serves
  resources :staffs
  resources :services
  resources :rooms
  resources :room_prices
  resources :payment_infos
  resources :hotels
  resources :checkins
  resources :buys
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ApplicationRecord
end

app/models/checkin.rb
class Checkin < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/payment_info.rb
class PaymentInfo < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/room_price.rb
class RoomPrice < ApplicationRecord
end

app/models/serve.rb
class Serve < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/controllers/payment_infos_controller.rb
class PaymentInfosController < ApplicationController
  before_action :set_payment_info, only: [:show, :edit, :update, :destroy]

  # GET /payment_infos
  # GET /payment_infos.json
  def index
    @payment_infos = PaymentInfo.all
  end

  # GET /payment_infos/1
  # GET /payment_infos/1.json
  def show
  end

  # GET /payment_infos/new
  def new
    @payment_info = PaymentInfo.new
  end

  # GET /payment_infos/1/edit
  def edit
  end

  # POST /payment_infos
  # POST /payment_infos.json
  def create
    @payment_info = PaymentInfo.new(payment_info_params)

    respond_to do |format|
      if @payment_info.save
        format.html { redirect_to @payment_info, notice: 'Payment info was successfully created.' }
        format.json { render :show, status: :created, location: @payment_info }
      else
        format.html { render :new }
        format.json { render json: @payment_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_infos/1
  # PATCH/PUT /payment_infos/1.json
  def update
    respond_to do |format|
      if @payment_info.update(payment_info_params)
        format.html { redirect_to @payment_info, notice: 'Payment info was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_info }
      else
        format.html { render :edit }
        format.json { render json: @payment_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_infos/1
  # DELETE /payment_infos/1.json
  def destroy
    @payment_info.destroy
    respond_to do |format|
      format.html { redirect_to payment_infos_url, notice: 'Payment info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_info
      @payment_info = PaymentInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_info_params
      params.require(:payment_info).permit(:SSN, :billingAddress, :City, :State, :Country, :paymentMethod, :cardNumber, :customerId)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/payment_infos_helper.rb
module PaymentInfosHelper
end

app/helpers/room_prices_helper.rb
module RoomPricesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/serves_helper.rb
module ServesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/payment_infos/_form.html.erb
<%= form_with(model: payment_info, local: true) do |form| %>
  <% if payment_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_info.errors.count, "error") %> prohibited this payment_info from being saved:</h2>

      <ul>
      <% payment_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :SSN %>
    <%= form.text_field :SSN, id: :payment_info_SSN %>
  </div>

  <div class="field">
    <%= form.label :billingAddress %>
    <%= form.text_field :billingAddress, id: :payment_info_billingAddress %>
  </div>

  <div class="field">
    <%= form.label :City %>
    <%= form.text_field :City, id: :payment_info_City %>
  </div>

  <div class="field">
    <%= form.label :State %>
    <%= form.text_field :State, id: :payment_info_State %>
  </div>

  <div class="field">
    <%= form.label :Country %>
    <%= form.text_field :Country, id: :payment_info_Country %>
  </div>

  <div class="field">
    <%= form.label :paymentMethod %>
    <%= form.text_field :paymentMethod, id: :payment_info_paymentMethod %>
  </div>

  <div class="field">
    <%= form.label :cardNumber %>
    <%= form.text_field :cardNumber, id: :payment_info_cardNumber %>
  </div>

  <div class="field">
    <%= form.label :customerId %>
    <%= form.number_field :customerId, id: :payment_info_customerId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payment_infos/edit.html.erb
<h1>Editing Payment Info</h1>

<%= render 'form', payment_info: @payment_info %>

<%= link_to 'Show', @payment_info %> |
<%= link_to 'Back', payment_infos_path %>

app/views/payment_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Infos</h1>

<table>
  <thead>
    <tr>
      <th>Ssn</th>
      <th>Billingaddress</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Paymentmethod</th>
      <th>Cardnumber</th>
      <th>Customerid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_infos.each do |payment_info| %>
      <tr>
        <td><%= payment_info.SSN %></td>
        <td><%= payment_info.billingAddress %></td>
        <td><%= payment_info.City %></td>
        <td><%= payment_info.State %></td>
        <td><%= payment_info.Country %></td>
        <td><%= payment_info.paymentMethod %></td>
        <td><%= payment_info.cardNumber %></td>
        <td><%= payment_info.customerId %></td>
        <td><%= link_to 'Show', payment_info %></td>
        <td><%= link_to 'Edit', edit_payment_info_path(payment_info) %></td>
        <td><%= link_to 'Destroy', payment_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment Info', new_payment_info_path %>

app/views/payment_infos/new.html.erb
<h1>New Payment Info</h1>

<%= render 'form', payment_info: @payment_info %>

<%= link_to 'Back', payment_infos_path %>

app/views/payment_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ssn:</strong>
  <%= @payment_info.SSN %>
</p>

<p>
  <strong>Billingaddress:</strong>
  <%= @payment_info.billingAddress %>
</p>

<p>
  <strong>City:</strong>
  <%= @payment_info.City %>
</p>

<p>
  <strong>State:</strong>
  <%= @payment_info.State %>
</p>

<p>
  <strong>Country:</strong>
  <%= @payment_info.Country %>
</p>

<p>
  <strong>Paymentmethod:</strong>
  <%= @payment_info.paymentMethod %>
</p>

<p>
  <strong>Cardnumber:</strong>
  <%= @payment_info.cardNumber %>
</p>

<p>
  <strong>Customerid:</strong>
  <%= @payment_info.customerId %>
</p>

<%= link_to 'Edit', edit_payment_info_path(@payment_info) %> |
<%= link_to 'Back', payment_infos_path %>