config/routes.rb
Rails.application.routes.draw do
  resources :serves
  resources :staffs
  resources :services
  resources :rooms
  resources :room_prices
  resources :payment_infos
  resources :hotels
  resources :checkins
  resources :buys
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ApplicationRecord
end

app/models/checkin.rb
class Checkin < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/payment_info.rb
class PaymentInfo < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/room_price.rb
class RoomPrice < ApplicationRecord
end

app/models/serve.rb
class Serve < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  # GET /buys
  # GET /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  # GET /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  # POST /buys.json
  def create
    @buy = Buy.new(buy_params)

    respond_to do |format|
      if @buy.save
        format.html { redirect_to @buy, notice: 'Buy was successfully created.' }
        format.json { render :show, status: :created, location: @buy }
      else
        format.html { render :new }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buys/1
  # PATCH/PUT /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: 'Buy was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy }
      else
        format.html { render :edit }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1
  # DELETE /buys/1.json
  def destroy
    @buy.destroy
    respond_to do |format|
      format.html { redirect_to buys_url, notice: 'Buy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_params
      params.require(:buy).permit(:serviceId, :checkinId, :price)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:roomNumber, :hotelId, :category, :maxOccupancy, :availability)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/room_prices_helper.rb
module RoomPricesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/serves_helper.rb
module ServesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/buys/_form.html.erb
<%= form_with(model: buy, local: true) do |form| %>
  <% if buy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buy.errors.count, "error") %> prohibited this buy from being saved:</h2>

      <ul>
      <% buy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :serviceId %>
    <%= form.number_field :serviceId, id: :buy_serviceId %>
  </div>

  <div class="field">
    <%= form.label :checkinId %>
    <%= form.number_field :checkinId, id: :buy_checkinId %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :buy_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buys/edit.html.erb
<h1>Editing Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Show', @buy %> |
<%= link_to 'Back', buys_path %>

app/views/buys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buys</h1>

<table>
  <thead>
    <tr>
      <th>Serviceid</th>
      <th>Checkinid</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buys.each do |buy| %>
      <tr>
        <td><%= buy.serviceId %></td>
        <td><%= buy.checkinId %></td>
        <td><%= buy.price %></td>
        <td><%= link_to 'Show', buy %></td>
        <td><%= link_to 'Edit', edit_buy_path(buy) %></td>
        <td><%= link_to 'Destroy', buy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buy', new_buy_path %>

app/views/buys/new.html.erb
<h1>New Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Back', buys_path %>

app/views/buys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Serviceid:</strong>
  <%= @buy.serviceId %>
</p>

<p>
  <strong>Checkinid:</strong>
  <%= @buy.checkinId %>
</p>

<p>
  <strong>Price:</strong>
  <%= @buy.price %>
</p>

<%= link_to 'Edit', edit_buy_path(@buy) %> |
<%= link_to 'Back', buys_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :roomNumber %>
    <%= form.number_field :roomNumber, id: :room_roomNumber %>
  </div>

  <div class="field">
    <%= form.label :hotelId %>
    <%= form.number_field :hotelId, id: :room_hotelId %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :room_category %>
  </div>

  <div class="field">
    <%= form.label :maxOccupancy %>
    <%= form.number_field :maxOccupancy, id: :room_maxOccupancy %>
  </div>

  <div class="field">
    <%= form.label :availability %>
    <%= form.check_box :availability, id: :room_availability %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Roomnumber</th>
      <th>Hotelid</th>
      <th>Category</th>
      <th>Maxoccupancy</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.roomNumber %></td>
        <td><%= room.hotelId %></td>
        <td><%= room.category %></td>
        <td><%= room.maxOccupancy %></td>
        <td><%= room.availability %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roomnumber:</strong>
  <%= @room.roomNumber %>
</p>

<p>
  <strong>Hotelid:</strong>
  <%= @room.hotelId %>
</p>

<p>
  <strong>Category:</strong>
  <%= @room.category %>
</p>

<p>
  <strong>Maxoccupancy:</strong>
  <%= @room.maxOccupancy %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @room.availability %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>